
package WS_Currency;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PServiceImpl", targetNamespace = "http://currencyWS/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCurrencyUnit", targetNamespace = "http://currencyWS/", className = "WS_Currency.GetCurrencyUnit")
    @ResponseWrapper(localName = "getCurrencyUnitResponse", targetNamespace = "http://currencyWS/", className = "WS_Currency.GetCurrencyUnitResponse")
    @Action(input = "http://currencyWS/PServiceImpl/getCurrencyUnitRequest", output = "http://currencyWS/PServiceImpl/getCurrencyUnitResponse")
    public String getCurrencyUnit(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
