
package WS_Multiplier;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PServiceImpl", targetNamespace = "http://PublishWS/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PServiceImpl {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiply", targetNamespace = "http://PublishWS/", className = "publishws.Multiply")
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://PublishWS/", className = "publishws.MultiplyResponse")
    @Action(input = "http://PublishWS/PServiceImpl/multiplyRequest", output = "http://PublishWS/PServiceImpl/multiplyResponse")
    public int multiply(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
